POST http://localhost:8880/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###

GET http://localhost:3435/test/list

###
GET http://localhost:3435/redis/set/123/12345

###
GET http://localhost:3435/redis/get/123